@baseUrl = http://localhost:3000
@tokenUser = TOKEN_AQUI
@tokenAdmin = ADMIN_TOKEN_AQUI

### 1. Adotar um Pet (Usuário Comum)
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "pet_id": 1
}

### 2. Tentar Adotar um Pet Já Adotado (Erro Esperado 409)
POST {{baseUrl}}/adoptions
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "pet_id": 1
}

# TESTE DE RELATÓRIO (Exige token de ADMIN)

### 3. Listar Histórico de Adoções (Administrador)
GET {{baseUrl}}/adoptions
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json