@baseUrl = http://localhost:3000
@token = TOKEN_AQUI

### 1. Listar Todos os Pets
GET {{baseUrl}}/pets
Content-Type: application/json

### 2. Buscar um Pet Específico
GET {{baseUrl}}/pets/1
Content-Type: application/json

# ROTAS PROTEGIDAS (Exigem a variável @token preenchida acima)

### 3. Cadastrar um Novo Pet (Apenas Administrador)
POST {{baseUrl}}/pets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bolinha",
  "birth_date": "2023-05-15",
  "gender": "male",
  "species": "Cachorro",
  "breed": "Poodle",
  "color": "Branco",
  "size": "small",
  "description": "Muito dócil, ideal para apartamentos pequenos."
}

### 4. Atualizar os dados de um Pet (Apenas Administrador)
PUT {{baseUrl}}/pets/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bolinha Atualizado",
  "color": "Branco com manchas pretas",
  "size": "medium"
}

### 5. Excluir um Pet (Soft Delete) (Apenas Administrador)
DELETE {{baseUrl}}/pets/5
Authorization: Bearer {{token}}